name: assignment_04
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  intl: ^0.19.0
  mocktail: ^1.0.4
  path: ^1.9.0
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.2
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
